import { appBaseUrl } from "../env";
import type { RunFailure } from "../storage/runs";

export const COMMENT_MARKER_PREFIX = "<!-- preview-reel:pr-";

export function commentMarker(prNumber: number): string {
  return `${COMMENT_MARKER_PREFIX}${prNumber} -->`;
}

function footer(): string {
  return `<sub>Generated by [Preview Reel](${appBaseUrl()})</sub>`;
}

function detailsBlock(detail: string): string {
  return detail.replaceAll("```", "``\u200b`");
}

export type CommentState =
  | { state: "in_progress"; title: string; statusUrl: string }
  | {
      state: "done";
      title: string;
      statusUrl: string;
      posterUrl: string;
      configUrl: string;
    }
  | {
      state: "failed";
      title: string;
      statusUrl: string;
      failure: RunFailure;
    };

export function renderComment(
  prNumber: number,
  state: CommentState,
): string {
  const marker = commentMarker(prNumber);

  if (state.state === "in_progress") {
    return [
      marker,
      "",
      "### Preview reels",
      "",
      "| Reel status | Details |",
      "| --- | --- |",
      `| In progress | Recording **${state.title}** on the preview. Usually takes about three minutes. |`,
      "",
      `[Watch progress](${state.statusUrl})`,
      "",
      footer(),
    ].join("\n");
  }

  if (state.state === "done") {
    return [
      marker,
      "",
      "### Preview reels",
      "",
      `[![${state.title}](${state.posterUrl})](${state.statusUrl})`,
      "",
      "| Reel status | Details |",
      "| --- | --- |",
      `| Ready | **${state.title}** |`,
      "",
      `[Watch the demo](${state.statusUrl}) · [View the recording config](${state.configUrl})`,
      "",
      footer(),
    ].join("\n");
  }

  return [
    marker,
    "",
    "### Preview reels",
    "",
    "| Reel status | Details |",
    "| --- | --- |",
    `| Failed | Recording **${state.title}** failed during **${state.failure.stage}**: ${state.failure.reason}. |`,
    "",
    "**Failure details**",
    "",
    "```text",
    detailsBlock(state.failure.detail),
    "```",
    "",
    `[View logs](${state.failure.logsUrl}) · [Retry](${state.statusUrl})`,
    "",
    footer(),
  ].join("\n");
}
